
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1
jobs:
  build-app:
    docker:
      - image: cimg/openjdk:15.0-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: |
          pwd
          node --version
          java --version
          google-chrome --version
      - run:    
          name: "install npm webserver"
          command: "npm install http-server"
      - run:
          background: true  
          command: "npx http-server"
  run-test:
    docker:
      - image: cimg/openjdk:15.0-browsers
    steps:
      - run:
          name: "run tests"
          command: "cd sample-test-java && mvn clean test"  
      - store_artifacts:
          path: /home/circleci/project/sample-test-java/target/cucumber-report/testreport.html
                   
workflows:
  run-tests-workflow:
    jobs:
      - build-app
      - run-test
