
version: 2.1
jobs:
  run-test:
    docker:
      - image: cimg/openjdk:15.0-browsers
    steps:
      - checkout
      - run:    
          name: "install npm webserver"
          command: "npm install http-server"
      - run:
          background: true  
          command: "npx http-server"
      - run:
          name: "run tests"
          command: "cd sample-test-java && mvn clean test"  

  # test-website:
  #   steps:
  #     - checkout
  #     - run:
  #         command: "cd sample-test-java && mvn clean test"             

workflows:
  run-tests-workflow:
    jobs:
      - run-test
